name: '[docker] CI for build tests'

on:
    pull_request:
        branches: master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v1
            with:
                version: latest
        -
            name: Build dockerfile (without push)
            run: |
                docker buildx build \
                --platform=linux/amd64 \
                --output "type=image,push=false" \
                --file ./Dockerfile .
